-- =============================================================================
-- 06_Security.sql
-- Principle of least privilege — app uses a dedicated SQL login with only
-- EXECUTE on stored procedures.  No direct table read/write permissions.
-- =============================================================================

USE [BruscaDb];
GO

-- ─── Application login (use SQL auth in dev; prefer Windows/MSI in prod) ─────
-- CREATE LOGIN [brusca_app] WITH PASSWORD = N'REPLACE_IN_PROD';
-- GO

-- ─── Application user mapped to login ────────────────────────────────────────
-- CREATE USER [brusca_app] FOR LOGIN [brusca_app];
-- GO

-- ─── Grant EXECUTE on each schema to application user ────────────────────────
-- GRANT EXECUTE ON SCHEMA::[cleaning]  TO [brusca_app];
-- GRANT EXECUTE ON SCHEMA::[fileext]   TO [brusca_app];
-- GRANT EXECUTE ON SCHEMA::[prompts]   TO [brusca_app];
-- GRANT EXECUTE ON SCHEMA::[security]  TO [brusca_app];
-- GRANT EXECUTE ON SCHEMA::[audit]     TO [brusca_app];
-- GRANT EXECUTE ON SCHEMA::[error]     TO [brusca_app];

-- ─── Deny direct table access ────────────────────────────────────────────────
-- DENY SELECT, INSERT, UPDATE, DELETE ON SCHEMA::[cleaning] TO [brusca_app];
-- (Repeat for all schemas — stored procedures elevate permissions at execute time)

-- ─── Audit read-only role (for log viewers) ───────────────────────────────────
-- CREATE ROLE [brusca_audit_reader];
-- GRANT SELECT ON [audit].[Log]  TO [brusca_audit_reader];
-- GRANT SELECT ON [error].[Log]  TO [brusca_audit_reader];

-- ─── Always Encrypted — Column Master Key metadata (run via SSMS wizard) ──────
-- The CMK is stored in Windows Certificate Store or Azure Key Vault.
-- This is a placeholder — actual key creation done outside T-SQL.
-- CREATE COLUMN MASTER KEY [CMK_BruscaApp]
-- WITH (
--     KEY_STORE_PROVIDER_NAME = N'MSSQL_CERTIFICATE_STORE',
--     KEY_PATH = N'CurrentUser/My/THUMBPRINT'
-- );
-- GO

-- CREATE COLUMN ENCRYPTION KEY [CEK_PII]
-- WITH VALUES (
--     COLUMN_MASTER_KEY = [CMK_BruscaApp],
--     ALGORITHM = 'RSA_OAEP',
--     ENCRYPTED_VALUE = 0x... -- generated by SSMS
-- );
-- GO

-- ─── Row-Level Security (example: users only see their own Cleanings) ─────────
-- CREATE FUNCTION [security].[fn_SecurityPredicate](@UserId NVARCHAR(256))
--     RETURNS TABLE WITH SCHEMABINDING
-- AS
--     RETURN SELECT 1 AS fn_Result
--            WHERE @UserId = CAST(SESSION_CONTEXT(N'UserId') AS NVARCHAR(256))
--               OR IS_MEMBER('db_owner') = 1;
-- GO

-- CREATE SECURITY POLICY [cleaning].[CleaningPolicy]
-- ADD FILTER PREDICATE [security].[fn_SecurityPredicate]([CreatedByUserId])
-- ON [cleaning].[Cleaning]
-- WITH (STATE = ON);
-- GO

PRINT '06_Security.sql: review and uncomment blocks as needed for your environment.';
